### ISSUE TITLE
yourWindows.GetPixelRGBColor(pos)

### ISSUE THREAD

**Issue by yw-teh** [mariobarbosa777/minwinpy#1]
Hi, thanks for api at first.
But it seem like i can get the windows name yet still cant print out the rgb. Any idea?
![image](https://user-images.githubusercontent.com/41685599/85425306-9b6f0200-b5ab-11ea-90a5-c73c37cd1a86.png)

**Comment by mariobarbosa777** [comment]
Let me check, i will answer you soonly,  but first are you running vs code as admin?

**Comment by mariobarbosa777** [comment]
I got the same error when i run vs code as no-admin, give admin permitions as  the next image show, 
![Issue1](https://user-images.githubusercontent.com/36166551/85443510-f591a800-b556-11ea-9613-82a261f8ef6e.PNG)

Restart Your Computer, try again and tell me if every thing is ok. i do the same and i got this 
![image](https://user-images.githubusercontent.com/36166551/85443701-34276280-b557-11ea-888d-ebf20c1caa06.png)

**Comment by mariobarbosa777** [comment]
Also try to run your windowsname as admin

**Comment by yw-teh** [comment]
I got it!! Thanks very much. Upvote your solution in stackoverflow too. Hope it will verified as correct solution
![image](https://user-images.githubusercontent.com/41685599/85593514-b27c2580-b679-11ea-8f2a-f89b9c6ceadf.png)

**Comment by mariobarbosa777** [comment]
Solve run as admin  vs-code  and your windows name
